### ISSUE TITLE
`0.5.0` tracker

### ISSUE THREAD

**Issue by brycx** [brycx/pasetors#60]
These are the things remaining before `0.5.0` can be released:

- [x] Add test that test the version features enabled individually not just all at the same time
- [x] Audit error-variants for usage and clarity in context
- [x] Run test-suite on 32-bit target using `cross`
- [x] Switch to RustCrypto `p384` crate once `0.11.0` has been released thereof, which will include P384 support (#55). RFC 6979 support still seems experimental, so we need to add an issue to switch to this in the future.
- [x] Update PASERK test vectors (#59)
- [x] Ensure fuzzing targets are up-to-date 

We'd also want to update the listing on paseto.io to indicate we support `v3.public`.

cc @Eh2406

**Comment by brycx** [comment]
`0.5.0` has been released on crates.io now as well.

**Comment by Eh2406** [comment]
Thank you!
